spring:
  application.name: otp-service
  port: 8080

  redis.host: localhost
  redis.port: 6379

  datasource.url: jdbc:h2:mem:test
  h2.console.enabled: true
  datasource.username: sa
  datasource.password: sa

notification-service:
  url: http://localhost:8082
  path: /sms

